/**
 * 1Backend
 * AI-native microservices platform.
 *
 * The version of the OpenAPI document: 0.8.0-rc2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ChatSvcEventMessageAdded } from './chatSvcEventMessageAdded';
import { ChatSvcEventThreadAdded } from './chatSvcEventThreadAdded';
import { ChatSvcEventThreadUpdate } from './chatSvcEventThreadUpdate';

export class Events200Response {
    'threadId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "threadId",
            "baseName": "threadId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Events200Response.attributeTypeMap;
    }
}

