/**
 * 1Backend
 * AI-native microservices platform.
 *
 * The version of the OpenAPI document: 0.8.0-rc6
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ModelSvcCudaParameters } from './modelSvcCudaParameters';
import { ModelSvcDefaultParameters } from './modelSvcDefaultParameters';

export class ModelSvcArchitectures {
    /**
    * CUDA-specific container parameters, if applicable.
    */
    'cuda'?: ModelSvcCudaParameters;
    /**
    * Default container configuration for non-GPU environments.
    */
    '_default'?: ModelSvcDefaultParameters;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cuda",
            "baseName": "cuda",
            "type": "ModelSvcCudaParameters"
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "ModelSvcDefaultParameters"
        }    ];

    static getAttributeTypeMap() {
        return ModelSvcArchitectures.attributeTypeMap;
    }
}

