/**
 * 1Backend
 * AI-native microservices platform.
 *
 * The version of the OpenAPI document: 0.8.0-rc3
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UserSvcAuthToken } from './userSvcAuthToken';
import { UserSvcOrganization } from './userSvcOrganization';

export class UserSvcSaveOrganizationResponse {
    'organization': UserSvcOrganization;
    'token': UserSvcAuthToken;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "organization",
            "baseName": "organization",
            "type": "UserSvcOrganization"
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "UserSvcAuthToken"
        }    ];

    static getAttributeTypeMap() {
        return UserSvcSaveOrganizationResponse.attributeTypeMap;
    }
}

