/**
 * 1Backend
 * AI-native microservices platform.
 *
 * The version of the OpenAPI document: 0.9.3
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UserSvcSendOtpResponse {
    /**
    * In test mode, the OTP code is returned in the response for easier testing.
    */
    'code'?: string;
    'otpId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "otpId",
            "baseName": "otpId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UserSvcSendOtpResponse.attributeTypeMap;
    }
}

