/**
 * 1Backend
 * AI-native microservices platform.
 *
 * The version of the OpenAPI document: 0.9.17
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UserSvcMembershipStatus } from './userSvcMembershipStatus';

export class UserSvcListMembershipsRequest {
    'afterTime'?: string;
    'limit'?: number;
    'organizationId'?: string;
    'status'?: UserSvcMembershipStatus;
    'userId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "afterTime",
            "baseName": "afterTime",
            "type": "string"
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number"
        },
        {
            "name": "organizationId",
            "baseName": "organizationId",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "UserSvcMembershipStatus"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UserSvcListMembershipsRequest.attributeTypeMap;
    }
}

export namespace UserSvcListMembershipsRequest {
}
