/*
1Backend

AI-native microservices platform.

API version: 0.9.12
Contact: sales@singulatron.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserSvcListMembershipsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserSvcListMembershipsResponse{}

// UserSvcListMembershipsResponse struct for UserSvcListMembershipsResponse
type UserSvcListMembershipsResponse struct {
	Memberships []UserSvcListMembershipsResponseMembershipsInner `json:"memberships"`
}

type _UserSvcListMembershipsResponse UserSvcListMembershipsResponse

// NewUserSvcListMembershipsResponse instantiates a new UserSvcListMembershipsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserSvcListMembershipsResponse(memberships []UserSvcListMembershipsResponseMembershipsInner) *UserSvcListMembershipsResponse {
	this := UserSvcListMembershipsResponse{}
	this.Memberships = memberships
	return &this
}

// NewUserSvcListMembershipsResponseWithDefaults instantiates a new UserSvcListMembershipsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserSvcListMembershipsResponseWithDefaults() *UserSvcListMembershipsResponse {
	this := UserSvcListMembershipsResponse{}
	return &this
}

// GetMemberships returns the Memberships field value
func (o *UserSvcListMembershipsResponse) GetMemberships() []UserSvcListMembershipsResponseMembershipsInner {
	if o == nil {
		var ret []UserSvcListMembershipsResponseMembershipsInner
		return ret
	}

	return o.Memberships
}

// GetMembershipsOk returns a tuple with the Memberships field value
// and a boolean to check if the value has been set.
func (o *UserSvcListMembershipsResponse) GetMembershipsOk() ([]UserSvcListMembershipsResponseMembershipsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Memberships, true
}

// SetMemberships sets field value
func (o *UserSvcListMembershipsResponse) SetMemberships(v []UserSvcListMembershipsResponseMembershipsInner) {
	o.Memberships = v
}

func (o UserSvcListMembershipsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserSvcListMembershipsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["memberships"] = o.Memberships
	return toSerialize, nil
}

func (o *UserSvcListMembershipsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"memberships",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserSvcListMembershipsResponse := _UserSvcListMembershipsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserSvcListMembershipsResponse)

	if err != nil {
		return err
	}

	*o = UserSvcListMembershipsResponse(varUserSvcListMembershipsResponse)

	return err
}

type NullableUserSvcListMembershipsResponse struct {
	value *UserSvcListMembershipsResponse
	isSet bool
}

func (v NullableUserSvcListMembershipsResponse) Get() *UserSvcListMembershipsResponse {
	return v.value
}

func (v *NullableUserSvcListMembershipsResponse) Set(val *UserSvcListMembershipsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUserSvcListMembershipsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUserSvcListMembershipsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserSvcListMembershipsResponse(val *UserSvcListMembershipsResponse) *NullableUserSvcListMembershipsResponse {
	return &NullableUserSvcListMembershipsResponse{value: val, isSet: true}
}

func (v NullableUserSvcListMembershipsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserSvcListMembershipsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


