/*
OpenOrch

A language-agnostic microservices framework for building AI applications.

API version: 0.3.0-rc.29
Contact: sales@singulatron.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UserSvcListGrantsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserSvcListGrantsRequest{}

// UserSvcListGrantsRequest struct for UserSvcListGrantsRequest
type UserSvcListGrantsRequest struct {
	PermissionId *string `json:"permissionId,omitempty"`
	Slug *string `json:"slug,omitempty"`
}

// NewUserSvcListGrantsRequest instantiates a new UserSvcListGrantsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserSvcListGrantsRequest() *UserSvcListGrantsRequest {
	this := UserSvcListGrantsRequest{}
	return &this
}

// NewUserSvcListGrantsRequestWithDefaults instantiates a new UserSvcListGrantsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserSvcListGrantsRequestWithDefaults() *UserSvcListGrantsRequest {
	this := UserSvcListGrantsRequest{}
	return &this
}

// GetPermissionId returns the PermissionId field value if set, zero value otherwise.
func (o *UserSvcListGrantsRequest) GetPermissionId() string {
	if o == nil || IsNil(o.PermissionId) {
		var ret string
		return ret
	}
	return *o.PermissionId
}

// GetPermissionIdOk returns a tuple with the PermissionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSvcListGrantsRequest) GetPermissionIdOk() (*string, bool) {
	if o == nil || IsNil(o.PermissionId) {
		return nil, false
	}
	return o.PermissionId, true
}

// HasPermissionId returns a boolean if a field has been set.
func (o *UserSvcListGrantsRequest) HasPermissionId() bool {
	if o != nil && !IsNil(o.PermissionId) {
		return true
	}

	return false
}

// SetPermissionId gets a reference to the given string and assigns it to the PermissionId field.
func (o *UserSvcListGrantsRequest) SetPermissionId(v string) {
	o.PermissionId = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *UserSvcListGrantsRequest) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSvcListGrantsRequest) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *UserSvcListGrantsRequest) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *UserSvcListGrantsRequest) SetSlug(v string) {
	o.Slug = &v
}

func (o UserSvcListGrantsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserSvcListGrantsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PermissionId) {
		toSerialize["permissionId"] = o.PermissionId
	}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	return toSerialize, nil
}

type NullableUserSvcListGrantsRequest struct {
	value *UserSvcListGrantsRequest
	isSet bool
}

func (v NullableUserSvcListGrantsRequest) Get() *UserSvcListGrantsRequest {
	return v.value
}

func (v *NullableUserSvcListGrantsRequest) Set(val *UserSvcListGrantsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserSvcListGrantsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserSvcListGrantsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserSvcListGrantsRequest(val *UserSvcListGrantsRequest) *NullableUserSvcListGrantsRequest {
	return &NullableUserSvcListGrantsRequest{value: val, isSet: true}
}

func (v NullableUserSvcListGrantsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserSvcListGrantsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


