/*
1Backend

AI-native microservices platform.

API version: 0.9.13
Contact: sales@singulatron.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UserSvcRevokeApiKeysRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserSvcRevokeApiKeysRequest{}

// UserSvcRevokeApiKeysRequest struct for UserSvcRevokeApiKeysRequest
type UserSvcRevokeApiKeysRequest struct {
	Id *string `json:"id,omitempty"`
	Ids []string `json:"ids,omitempty"`
	UserId *string `json:"userId,omitempty"`
}

// NewUserSvcRevokeApiKeysRequest instantiates a new UserSvcRevokeApiKeysRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserSvcRevokeApiKeysRequest() *UserSvcRevokeApiKeysRequest {
	this := UserSvcRevokeApiKeysRequest{}
	return &this
}

// NewUserSvcRevokeApiKeysRequestWithDefaults instantiates a new UserSvcRevokeApiKeysRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserSvcRevokeApiKeysRequestWithDefaults() *UserSvcRevokeApiKeysRequest {
	this := UserSvcRevokeApiKeysRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UserSvcRevokeApiKeysRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSvcRevokeApiKeysRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UserSvcRevokeApiKeysRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UserSvcRevokeApiKeysRequest) SetId(v string) {
	o.Id = &v
}

// GetIds returns the Ids field value if set, zero value otherwise.
func (o *UserSvcRevokeApiKeysRequest) GetIds() []string {
	if o == nil || IsNil(o.Ids) {
		var ret []string
		return ret
	}
	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSvcRevokeApiKeysRequest) GetIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.Ids) {
		return nil, false
	}
	return o.Ids, true
}

// HasIds returns a boolean if a field has been set.
func (o *UserSvcRevokeApiKeysRequest) HasIds() bool {
	if o != nil && !IsNil(o.Ids) {
		return true
	}

	return false
}

// SetIds gets a reference to the given []string and assigns it to the Ids field.
func (o *UserSvcRevokeApiKeysRequest) SetIds(v []string) {
	o.Ids = v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *UserSvcRevokeApiKeysRequest) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSvcRevokeApiKeysRequest) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *UserSvcRevokeApiKeysRequest) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *UserSvcRevokeApiKeysRequest) SetUserId(v string) {
	o.UserId = &v
}

func (o UserSvcRevokeApiKeysRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserSvcRevokeApiKeysRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Ids) {
		toSerialize["ids"] = o.Ids
	}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	return toSerialize, nil
}

type NullableUserSvcRevokeApiKeysRequest struct {
	value *UserSvcRevokeApiKeysRequest
	isSet bool
}

func (v NullableUserSvcRevokeApiKeysRequest) Get() *UserSvcRevokeApiKeysRequest {
	return v.value
}

func (v *NullableUserSvcRevokeApiKeysRequest) Set(val *UserSvcRevokeApiKeysRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserSvcRevokeApiKeysRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserSvcRevokeApiKeysRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserSvcRevokeApiKeysRequest(val *UserSvcRevokeApiKeysRequest) *NullableUserSvcRevokeApiKeysRequest {
	return &NullableUserSvcRevokeApiKeysRequest{value: val, isSet: true}
}

func (v NullableUserSvcRevokeApiKeysRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserSvcRevokeApiKeysRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


