/*
1Backend

AI-native microservices platform.

API version: 0.9.12
Contact: sales@singulatron.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProxySvcListRedirectsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProxySvcListRedirectsRequest{}

// ProxySvcListRedirectsRequest struct for ProxySvcListRedirectsRequest
type ProxySvcListRedirectsRequest struct {
	Ids []string `json:"ids,omitempty"`
}

// NewProxySvcListRedirectsRequest instantiates a new ProxySvcListRedirectsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProxySvcListRedirectsRequest() *ProxySvcListRedirectsRequest {
	this := ProxySvcListRedirectsRequest{}
	return &this
}

// NewProxySvcListRedirectsRequestWithDefaults instantiates a new ProxySvcListRedirectsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProxySvcListRedirectsRequestWithDefaults() *ProxySvcListRedirectsRequest {
	this := ProxySvcListRedirectsRequest{}
	return &this
}

// GetIds returns the Ids field value if set, zero value otherwise.
func (o *ProxySvcListRedirectsRequest) GetIds() []string {
	if o == nil || IsNil(o.Ids) {
		var ret []string
		return ret
	}
	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProxySvcListRedirectsRequest) GetIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.Ids) {
		return nil, false
	}
	return o.Ids, true
}

// HasIds returns a boolean if a field has been set.
func (o *ProxySvcListRedirectsRequest) HasIds() bool {
	if o != nil && !IsNil(o.Ids) {
		return true
	}

	return false
}

// SetIds gets a reference to the given []string and assigns it to the Ids field.
func (o *ProxySvcListRedirectsRequest) SetIds(v []string) {
	o.Ids = v
}

func (o ProxySvcListRedirectsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProxySvcListRedirectsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ids) {
		toSerialize["ids"] = o.Ids
	}
	return toSerialize, nil
}

type NullableProxySvcListRedirectsRequest struct {
	value *ProxySvcListRedirectsRequest
	isSet bool
}

func (v NullableProxySvcListRedirectsRequest) Get() *ProxySvcListRedirectsRequest {
	return v.value
}

func (v *NullableProxySvcListRedirectsRequest) Set(val *ProxySvcListRedirectsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProxySvcListRedirectsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProxySvcListRedirectsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProxySvcListRedirectsRequest(val *ProxySvcListRedirectsRequest) *NullableProxySvcListRedirectsRequest {
	return &NullableProxySvcListRedirectsRequest{value: val, isSet: true}
}

func (v NullableProxySvcListRedirectsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProxySvcListRedirectsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


