/*
1Backend

AI-native microservices platform.

API version: 0.3.0-rc.31
Contact: sales@singulatron.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserSvcPermissionLink type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserSvcPermissionLink{}

// UserSvcPermissionLink struct for UserSvcPermissionLink
type UserSvcPermissionLink struct {
	PermissionId string `json:"permissionId"`
	RoleId string `json:"roleId"`
}

type _UserSvcPermissionLink UserSvcPermissionLink

// NewUserSvcPermissionLink instantiates a new UserSvcPermissionLink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserSvcPermissionLink(permissionId string, roleId string) *UserSvcPermissionLink {
	this := UserSvcPermissionLink{}
	this.PermissionId = permissionId
	this.RoleId = roleId
	return &this
}

// NewUserSvcPermissionLinkWithDefaults instantiates a new UserSvcPermissionLink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserSvcPermissionLinkWithDefaults() *UserSvcPermissionLink {
	this := UserSvcPermissionLink{}
	return &this
}

// GetPermissionId returns the PermissionId field value
func (o *UserSvcPermissionLink) GetPermissionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PermissionId
}

// GetPermissionIdOk returns a tuple with the PermissionId field value
// and a boolean to check if the value has been set.
func (o *UserSvcPermissionLink) GetPermissionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PermissionId, true
}

// SetPermissionId sets field value
func (o *UserSvcPermissionLink) SetPermissionId(v string) {
	o.PermissionId = v
}

// GetRoleId returns the RoleId field value
func (o *UserSvcPermissionLink) GetRoleId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoleId
}

// GetRoleIdOk returns a tuple with the RoleId field value
// and a boolean to check if the value has been set.
func (o *UserSvcPermissionLink) GetRoleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleId, true
}

// SetRoleId sets field value
func (o *UserSvcPermissionLink) SetRoleId(v string) {
	o.RoleId = v
}

func (o UserSvcPermissionLink) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserSvcPermissionLink) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["permissionId"] = o.PermissionId
	toSerialize["roleId"] = o.RoleId
	return toSerialize, nil
}

func (o *UserSvcPermissionLink) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"permissionId",
		"roleId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserSvcPermissionLink := _UserSvcPermissionLink{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserSvcPermissionLink)

	if err != nil {
		return err
	}

	*o = UserSvcPermissionLink(varUserSvcPermissionLink)

	return err
}

type NullableUserSvcPermissionLink struct {
	value *UserSvcPermissionLink
	isSet bool
}

func (v NullableUserSvcPermissionLink) Get() *UserSvcPermissionLink {
	return v.value
}

func (v *NullableUserSvcPermissionLink) Set(val *UserSvcPermissionLink) {
	v.value = val
	v.isSet = true
}

func (v NullableUserSvcPermissionLink) IsSet() bool {
	return v.isSet
}

func (v *NullableUserSvcPermissionLink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserSvcPermissionLink(val *UserSvcPermissionLink) *NullableUserSvcPermissionLink {
	return &NullableUserSvcPermissionLink{value: val, isSet: true}
}

func (v NullableUserSvcPermissionLink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserSvcPermissionLink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


