/* tslint:disable */
/* eslint-disable */
/**
 * Basic Svc
 * An example service for bootstrapping.
 *
 * The version of the OpenAPI document: 0.3.0-rc.8
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BasicSvcPet } from './BasicSvcPet';
import {
    BasicSvcPetFromJSON,
    BasicSvcPetFromJSONTyped,
    BasicSvcPetToJSON,
    BasicSvcPetToJSONTyped,
} from './BasicSvcPet';

/**
 * 
 * @export
 * @interface BasicSvcListPetsResponse
 */
export interface BasicSvcListPetsResponse {
    /**
     * 
     * @type {Array<BasicSvcPet>}
     * @memberof BasicSvcListPetsResponse
     */
    pets?: Array<BasicSvcPet>;
}

/**
 * Check if a given object implements the BasicSvcListPetsResponse interface.
 */
export function instanceOfBasicSvcListPetsResponse(value: object): value is BasicSvcListPetsResponse {
    return true;
}

export function BasicSvcListPetsResponseFromJSON(json: any): BasicSvcListPetsResponse {
    return BasicSvcListPetsResponseFromJSONTyped(json, false);
}

export function BasicSvcListPetsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BasicSvcListPetsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pets': json['pets'] == null ? undefined : ((json['pets'] as Array<any>).map(BasicSvcPetFromJSON)),
    };
}

export function BasicSvcListPetsResponseToJSON(json: any): BasicSvcListPetsResponse {
    return BasicSvcListPetsResponseToJSONTyped(json, false);
}

export function BasicSvcListPetsResponseToJSONTyped(value?: BasicSvcListPetsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pets': value['pets'] == null ? undefined : ((value['pets'] as Array<any>).map(BasicSvcPetToJSON)),
    };
}

