/*
Basic Svc

An example service for bootstrapping.

API version: 0.3.0-rc.8
Contact: sales@singulatron.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BasicSvcSavePetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BasicSvcSavePetRequest{}

// BasicSvcSavePetRequest struct for BasicSvcSavePetRequest
type BasicSvcSavePetRequest struct {
	Id *string `json:"id,omitempty"`
	Name string `json:"name"`
}

type _BasicSvcSavePetRequest BasicSvcSavePetRequest

// NewBasicSvcSavePetRequest instantiates a new BasicSvcSavePetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBasicSvcSavePetRequest(name string) *BasicSvcSavePetRequest {
	this := BasicSvcSavePetRequest{}
	this.Name = name
	return &this
}

// NewBasicSvcSavePetRequestWithDefaults instantiates a new BasicSvcSavePetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBasicSvcSavePetRequestWithDefaults() *BasicSvcSavePetRequest {
	this := BasicSvcSavePetRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *BasicSvcSavePetRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasicSvcSavePetRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *BasicSvcSavePetRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *BasicSvcSavePetRequest) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value
func (o *BasicSvcSavePetRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BasicSvcSavePetRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BasicSvcSavePetRequest) SetName(v string) {
	o.Name = v
}

func (o BasicSvcSavePetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BasicSvcSavePetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *BasicSvcSavePetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBasicSvcSavePetRequest := _BasicSvcSavePetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBasicSvcSavePetRequest)

	if err != nil {
		return err
	}

	*o = BasicSvcSavePetRequest(varBasicSvcSavePetRequest)

	return err
}

type NullableBasicSvcSavePetRequest struct {
	value *BasicSvcSavePetRequest
	isSet bool
}

func (v NullableBasicSvcSavePetRequest) Get() *BasicSvcSavePetRequest {
	return v.value
}

func (v *NullableBasicSvcSavePetRequest) Set(val *BasicSvcSavePetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBasicSvcSavePetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBasicSvcSavePetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBasicSvcSavePetRequest(val *BasicSvcSavePetRequest) *NullableBasicSvcSavePetRequest {
	return &NullableBasicSvcSavePetRequest{value: val, isSet: true}
}

func (v NullableBasicSvcSavePetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBasicSvcSavePetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


