/* tslint:disable */
/* eslint-disable */
/**
 * 1Backend
 * AI-native microservices platform.
 *
 * The version of the OpenAPI document: 0.9.1
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSvcListAppsRequest
 */
export interface UserSvcListAppsRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof UserSvcListAppsRequest
     */
    host?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserSvcListAppsRequest
     */
    ids?: Array<string>;
}

/**
 * Check if a given object implements the UserSvcListAppsRequest interface.
 */
export function instanceOfUserSvcListAppsRequest(value: object): value is UserSvcListAppsRequest {
    return true;
}

export function UserSvcListAppsRequestFromJSON(json: any): UserSvcListAppsRequest {
    return UserSvcListAppsRequestFromJSONTyped(json, false);
}

export function UserSvcListAppsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSvcListAppsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'host': json['host'] == null ? undefined : json['host'],
        'ids': json['ids'] == null ? undefined : json['ids'],
    };
}

export function UserSvcListAppsRequestToJSON(json: any): UserSvcListAppsRequest {
    return UserSvcListAppsRequestToJSONTyped(json, false);
}

export function UserSvcListAppsRequestToJSONTyped(value?: UserSvcListAppsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'host': value['host'],
        'ids': value['ids'],
    };
}

