/* tslint:disable */
/* eslint-disable */
/**
 * 1Backend
 * AI-native microservices platform.
 *
 * The version of the OpenAPI document: 0.9.17
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSvcCreateApiKeyRequest
 */
export interface UserSvcCreateApiKeyRequest {
    /**
     * ActiveOrganizationId is optional. If omitted, the current token's active
     * organization is used. If explicitly set to an empty string, the API key
     * authenticates without an active organization.
     * @type {string}
     * @memberof UserSvcCreateApiKeyRequest
     */
    activeOrganizationId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSvcCreateApiKeyRequest
     */
    appHost?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSvcCreateApiKeyRequest
     */
    appId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSvcCreateApiKeyRequest
     */
    expiresAt?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSvcCreateApiKeyRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSvcCreateApiKeyRequest
     */
    userId?: string;
}

/**
 * Check if a given object implements the UserSvcCreateApiKeyRequest interface.
 */
export function instanceOfUserSvcCreateApiKeyRequest(value: object): value is UserSvcCreateApiKeyRequest {
    return true;
}

export function UserSvcCreateApiKeyRequestFromJSON(json: any): UserSvcCreateApiKeyRequest {
    return UserSvcCreateApiKeyRequestFromJSONTyped(json, false);
}

export function UserSvcCreateApiKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSvcCreateApiKeyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'activeOrganizationId': json['activeOrganizationId'] == null ? undefined : json['activeOrganizationId'],
        'appHost': json['appHost'] == null ? undefined : json['appHost'],
        'appId': json['appId'] == null ? undefined : json['appId'],
        'expiresAt': json['expiresAt'] == null ? undefined : json['expiresAt'],
        'name': json['name'] == null ? undefined : json['name'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function UserSvcCreateApiKeyRequestToJSON(json: any): UserSvcCreateApiKeyRequest {
    return UserSvcCreateApiKeyRequestToJSONTyped(json, false);
}

export function UserSvcCreateApiKeyRequestToJSONTyped(value?: UserSvcCreateApiKeyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activeOrganizationId': value['activeOrganizationId'],
        'appHost': value['appHost'],
        'appId': value['appId'],
        'expiresAt': value['expiresAt'],
        'name': value['name'],
        'userId': value['userId'],
    };
}

