/* tslint:disable */
/* eslint-disable */
/**
 * 1Backend
 * AI-native microservices platform.
 *
 * The version of the OpenAPI document: 0.9.15
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSvcApiKeyView
 */
export interface UserSvcApiKeyView {
    /**
     * 
     * @type {string}
     * @memberof UserSvcApiKeyView
     */
    activeOrganizationId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSvcApiKeyView
     */
    appId: string;
    /**
     * 
     * @type {string}
     * @memberof UserSvcApiKeyView
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof UserSvcApiKeyView
     */
    expiresAt?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSvcApiKeyView
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserSvcApiKeyView
     */
    lastUsedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSvcApiKeyView
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSvcApiKeyView
     */
    prefix?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSvcApiKeyView
     */
    revokedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSvcApiKeyView
     */
    updatedAt: string;
    /**
     * 
     * @type {string}
     * @memberof UserSvcApiKeyView
     */
    userId: string;
}

/**
 * Check if a given object implements the UserSvcApiKeyView interface.
 */
export function instanceOfUserSvcApiKeyView(value: object): value is UserSvcApiKeyView {
    if (!('appId' in value) || value['appId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function UserSvcApiKeyViewFromJSON(json: any): UserSvcApiKeyView {
    return UserSvcApiKeyViewFromJSONTyped(json, false);
}

export function UserSvcApiKeyViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSvcApiKeyView {
    if (json == null) {
        return json;
    }
    return {
        
        'activeOrganizationId': json['activeOrganizationId'] == null ? undefined : json['activeOrganizationId'],
        'appId': json['appId'],
        'createdAt': json['createdAt'],
        'expiresAt': json['expiresAt'] == null ? undefined : json['expiresAt'],
        'id': json['id'],
        'lastUsedAt': json['lastUsedAt'] == null ? undefined : json['lastUsedAt'],
        'name': json['name'] == null ? undefined : json['name'],
        'prefix': json['prefix'] == null ? undefined : json['prefix'],
        'revokedAt': json['revokedAt'] == null ? undefined : json['revokedAt'],
        'updatedAt': json['updatedAt'],
        'userId': json['userId'],
    };
}

export function UserSvcApiKeyViewToJSON(json: any): UserSvcApiKeyView {
    return UserSvcApiKeyViewToJSONTyped(json, false);
}

export function UserSvcApiKeyViewToJSONTyped(value?: UserSvcApiKeyView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activeOrganizationId': value['activeOrganizationId'],
        'appId': value['appId'],
        'createdAt': value['createdAt'],
        'expiresAt': value['expiresAt'],
        'id': value['id'],
        'lastUsedAt': value['lastUsedAt'],
        'name': value['name'],
        'prefix': value['prefix'],
        'revokedAt': value['revokedAt'],
        'updatedAt': value['updatedAt'],
        'userId': value['userId'],
    };
}

