/* tslint:disable */
/* eslint-disable */
/**
 * 1Backend
 * AI-native microservices platform.
 *
 * The version of the OpenAPI document: 0.9.17
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserSvcToken } from './UserSvcToken';
import {
    UserSvcTokenFromJSON,
    UserSvcTokenFromJSONTyped,
    UserSvcTokenToJSON,
    UserSvcTokenToJSONTyped,
} from './UserSvcToken';

/**
 * 
 * @export
 * @interface UserSvcActivateOrganizationResponse
 */
export interface UserSvcActivateOrganizationResponse {
    /**
     * 
     * @type {UserSvcToken}
     * @memberof UserSvcActivateOrganizationResponse
     */
    token: UserSvcToken;
}

/**
 * Check if a given object implements the UserSvcActivateOrganizationResponse interface.
 */
export function instanceOfUserSvcActivateOrganizationResponse(value: object): value is UserSvcActivateOrganizationResponse {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function UserSvcActivateOrganizationResponseFromJSON(json: any): UserSvcActivateOrganizationResponse {
    return UserSvcActivateOrganizationResponseFromJSONTyped(json, false);
}

export function UserSvcActivateOrganizationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSvcActivateOrganizationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': UserSvcTokenFromJSON(json['token']),
    };
}

export function UserSvcActivateOrganizationResponseToJSON(json: any): UserSvcActivateOrganizationResponse {
    return UserSvcActivateOrganizationResponseToJSONTyped(json, false);
}

export function UserSvcActivateOrganizationResponseToJSONTyped(value?: UserSvcActivateOrganizationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': UserSvcTokenToJSON(value['token']),
    };
}

