/* tslint:disable */
/* eslint-disable */
/**
 * 1Backend
 * AI-native microservices platform.
 *
 * The version of the OpenAPI document: 0.9.1
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ImageSvcErrorResponse,
} from '../models/index';
import {
    ImageSvcErrorResponseFromJSON,
    ImageSvcErrorResponseToJSON,
} from '../models/index';

export interface ServeUploadedImageRequest {
    fileId: string;
    width?: number;
    height?: number;
}

/**
 * 
 */
export class ImageSvcApi extends runtime.BaseAPI {

    /**
     * Retrieves and serves a previously uploaded image file using its File ID.
     * Serve Uploaded Image
     */
    async serveUploadedImageRaw(requestParameters: ServeUploadedImageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling serveUploadedImage().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['width'] != null) {
            queryParameters['width'] = requestParameters['width'];
        }

        if (requestParameters['height'] != null) {
            queryParameters['height'] = requestParameters['height'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/image-svc/serve/upload/{fileId}`;
        urlPath = urlPath.replace(`{${"fileId"}}`, encodeURIComponent(String(requestParameters['fileId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Retrieves and serves a previously uploaded image file using its File ID.
     * Serve Uploaded Image
     */
    async serveUploadedImage(requestParameters: ServeUploadedImageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.serveUploadedImageRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
