/* tslint:disable */
/* eslint-disable */
/**
 * 1Backend
 * AI-native microservices platform.
 *
 * The version of the OpenAPI document: 0.9.18
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProxySvcDeleteRedirectsRequest,
  ProxySvcDeleteRoutesRequest,
  ProxySvcErrorResponse,
  ProxySvcListCertsRequest,
  ProxySvcListCertsResponse,
  ProxySvcListRedirectsRequest,
  ProxySvcListRedirectsResponse,
  ProxySvcListRoutesRequest,
  ProxySvcListRoutesResponse,
  ProxySvcSaveCertsRequest,
  ProxySvcSaveRedirectsRequest,
  ProxySvcSaveRedirectsResponse,
  ProxySvcSaveRoutesRequest,
  ProxySvcSaveRoutesResponse,
} from '../models/index';
import {
    ProxySvcDeleteRedirectsRequestFromJSON,
    ProxySvcDeleteRedirectsRequestToJSON,
    ProxySvcDeleteRoutesRequestFromJSON,
    ProxySvcDeleteRoutesRequestToJSON,
    ProxySvcErrorResponseFromJSON,
    ProxySvcErrorResponseToJSON,
    ProxySvcListCertsRequestFromJSON,
    ProxySvcListCertsRequestToJSON,
    ProxySvcListCertsResponseFromJSON,
    ProxySvcListCertsResponseToJSON,
    ProxySvcListRedirectsRequestFromJSON,
    ProxySvcListRedirectsRequestToJSON,
    ProxySvcListRedirectsResponseFromJSON,
    ProxySvcListRedirectsResponseToJSON,
    ProxySvcListRoutesRequestFromJSON,
    ProxySvcListRoutesRequestToJSON,
    ProxySvcListRoutesResponseFromJSON,
    ProxySvcListRoutesResponseToJSON,
    ProxySvcSaveCertsRequestFromJSON,
    ProxySvcSaveCertsRequestToJSON,
    ProxySvcSaveRedirectsRequestFromJSON,
    ProxySvcSaveRedirectsRequestToJSON,
    ProxySvcSaveRedirectsResponseFromJSON,
    ProxySvcSaveRedirectsResponseToJSON,
    ProxySvcSaveRoutesRequestFromJSON,
    ProxySvcSaveRoutesRequestToJSON,
    ProxySvcSaveRoutesResponseFromJSON,
    ProxySvcSaveRoutesResponseToJSON,
} from '../models/index';

export interface DeleteRedirectsRequest {
    body: ProxySvcDeleteRedirectsRequest;
}

export interface DeleteRoutesRequest {
    body: ProxySvcDeleteRoutesRequest;
}

export interface ListCertsRequest {
    body?: ProxySvcListCertsRequest;
}

export interface ListRedirectsRequest {
    body?: ProxySvcListRedirectsRequest;
}

export interface ListRoutesRequest {
    body?: ProxySvcListRoutesRequest;
}

export interface SaveCertsRequest {
    body: ProxySvcSaveCertsRequest;
}

export interface SaveRedirectsRequest {
    body: ProxySvcSaveRedirectsRequest;
}

export interface SaveRoutesRequest {
    body: ProxySvcSaveRoutesRequest;
}

/**
 * 
 */
export class ProxySvcApi extends runtime.BaseAPI {

    /**
     * Delete specific redirects by their IDs.
     * Delete Redirects
     */
    async deleteRedirectsRaw(requestParameters: DeleteRedirectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling deleteRedirects().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/proxy-svc/redirects`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: ProxySvcDeleteRedirectsRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Delete specific redirects by their IDs.
     * Delete Redirects
     */
    async deleteRedirects(requestParameters: DeleteRedirectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.deleteRedirectsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete specific routes by their IDs.
     * Delete Routes
     */
    async deleteRoutesRaw(requestParameters: DeleteRoutesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling deleteRoutes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/proxy-svc/routes`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: ProxySvcDeleteRoutesRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Delete specific routes by their IDs.
     * Delete Routes
     */
    async deleteRoutes(requestParameters: DeleteRoutesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.deleteRoutesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List certs that the edge proxy will use to cert requests.
     * List Certs
     */
    async listCertsRaw(requestParameters: ListCertsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProxySvcListCertsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/proxy-svc/certs`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProxySvcListCertsRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProxySvcListCertsResponseFromJSON(jsonValue));
    }

    /**
     * List certs that the edge proxy will use to cert requests.
     * List Certs
     */
    async listCerts(requestParameters: ListCertsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProxySvcListCertsResponse> {
        const response = await this.listCertsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List redirects that the edge proxy applies before routing requests.
     * List Redirects
     */
    async listRedirectsRaw(requestParameters: ListRedirectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProxySvcListRedirectsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/proxy-svc/redirects`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProxySvcListRedirectsRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProxySvcListRedirectsResponseFromJSON(jsonValue));
    }

    /**
     * List redirects that the edge proxy applies before routing requests.
     * List Redirects
     */
    async listRedirects(requestParameters: ListRedirectsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProxySvcListRedirectsResponse> {
        const response = await this.listRedirectsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List routes that the edge proxy will use to route requests.
     * List Routes
     */
    async listRoutesRaw(requestParameters: ListRoutesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProxySvcListRoutesResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/proxy-svc/routes`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProxySvcListRoutesRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProxySvcListRoutesResponseFromJSON(jsonValue));
    }

    /**
     * List routes that the edge proxy will use to route requests.
     * List Routes
     */
    async listRoutes(requestParameters: ListRoutesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProxySvcListRoutesResponse> {
        const response = await this.listRoutesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint only exist for testing purposes. Only callable by admins Certs should be saved by the Proxy Svc and its edge proxying functionality internally, not through this endpoint.
     * Save Certs
     */
    async saveCertsRaw(requestParameters: SaveCertsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling saveCerts().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/proxy-svc/certs`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ProxySvcSaveCertsRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * This endpoint only exist for testing purposes. Only callable by admins Certs should be saved by the Proxy Svc and its edge proxying functionality internally, not through this endpoint.
     * Save Certs
     */
    async saveCerts(requestParameters: SaveCertsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.saveCertsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Save redirects that the edge proxy will apply before routing requests.
     * Save Redirects
     */
    async saveRedirectsRaw(requestParameters: SaveRedirectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProxySvcSaveRedirectsResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling saveRedirects().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/proxy-svc/redirects`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ProxySvcSaveRedirectsRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProxySvcSaveRedirectsResponseFromJSON(jsonValue));
    }

    /**
     * Save redirects that the edge proxy will apply before routing requests.
     * Save Redirects
     */
    async saveRedirects(requestParameters: SaveRedirectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProxySvcSaveRedirectsResponse> {
        const response = await this.saveRedirectsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Save routes that the edge proxy will use to route requests.
     * Save Routes
     */
    async saveRoutesRaw(requestParameters: SaveRoutesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProxySvcSaveRoutesResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling saveRoutes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/proxy-svc/routes`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ProxySvcSaveRoutesRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProxySvcSaveRoutesResponseFromJSON(jsonValue));
    }

    /**
     * Save routes that the edge proxy will use to route requests.
     * Save Routes
     */
    async saveRoutes(requestParameters: SaveRoutesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProxySvcSaveRoutesResponse> {
        const response = await this.saveRoutesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
