version: "3.8"

volumes:
  openorch--data:
    name: openorch--data
    driver: local

services:
  openorch-frontend:
    image: crufter/openorch--frontend:latest
    ports:
      - "3901:80"
    environment:
      # The `BACKEND_ADDRESS` must be accessible from the   browser.
      # It is not an internal address, it's the address the   browser will make API requests to.
      - BACKEND_ADDRESS=http://127.0.0.1:58231

  openorch-backend:
    image: crufter/openorch--backend:latest
    # use this if you have an nvidia card
    # build: ./localtron/docker/DockerfileNvidia
    ports:
      - "58231:58231"
    volumes:
      # We mount the hostname to have a sensible fallback node URL
      - /etc/hostname:/etc/host_hostname:ro
      # We mount the docker socket so the backend can start containers
      - /var/run/docker.sock:/var/run/docker.sock
      # We mount a volume so data will be persisted
      - openorch--data:/root/.openorch-
    environment:
      # This volume will be mounted by the LLM containers to access the models downloaded by OpenOrch.
      - OPENORCH_VOLUME_NAME=openorch--data
      # Address of the host so we can access the containers running the LLMs from the backend container
      # See "System Specific Settings" on this page for more information.
      - OPENORCH_LLM_HOST=172.17.0.1
      #
      # GPU Acceleration for NVIDIA GPUs
      # Uncomment this envar for NVIDIA GPUs.
      #
      # - OPENORCH_GPU_PLATFORM=cuda
