basePath: /
definitions:
  basic_svc.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  basic_svc.ListPetsRequest:
    type: object
  basic_svc.ListPetsResponse:
    properties:
      pets:
        items:
          $ref: '#/definitions/basic_svc.Pet'
        type: array
    type: object
  basic_svc.Pet:
    properties:
      createdAt:
        type: string
      id:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    required:
    - createdAt
    - id
    - updatedAt
    type: object
  basic_svc.SavePetRequest:
    properties:
      id:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  basic_svc.SavePetResponse:
    type: object
host: localhost:11337
info:
  contact:
    email: sales@singulatron.com
    name: API Support
    url: https://1backend.com/
  description: An example service for bootstrapping.
  license:
    name: Proprietary
  termsOfService: http://swagger.io/terms/
  title: Basic Svc
  version: 0.3.0-rc.8
paths:
  /basic-svc/error:
    post:
      consumes:
      - application/json
      description: This endpoint simply errors. Useful for testing the proxy.
      operationId: error
      produces:
      - application/json
      responses:
        "500":
          description: Error
          schema:
            $ref: '#/definitions/basic_svc.ErrorResponse'
      summary: Error
      tags:
      - Basic Svc
  /basic-svc/pet:
    put:
      consumes:
      - application/json
      description: Save a pet for a user and an organization.
      operationId: savePet
      parameters:
      - description: Registration Tracking Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/basic_svc.SavePetRequest'
      produces:
      - application/json
      responses:
        "200":
          description: '{}'
          schema:
            $ref: '#/definitions/basic_svc.SavePetResponse'
        "400":
          description: Invalid Pet
          schema:
            $ref: '#/definitions/basic_svc.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/basic_svc.ErrorResponse'
      summary: Save Pet
      tags:
      - Basic Svc
  /basic-svc/pets:
    post:
      consumes:
      - application/json
      description: List pets.
      operationId: listPets
      parameters:
      - description: List Pets Request
        in: body
        name: body
        schema:
          $ref: '#/definitions/basic_svc.ListPetsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: '{}'
          schema:
            $ref: '#/definitions/basic_svc.ListPetsResponse'
        "400":
          description: Invalid JSON
          schema:
            $ref: '#/definitions/basic_svc.ErrorResponse'
        "500":
          description: Error Listing Pets
          schema:
            $ref: '#/definitions/basic_svc.ErrorResponse'
      summary: List Pets
      tags:
      - Basic Svc
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and token acquired from the User
      Svc Login endpoint.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
