name: CLI OO build

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.23.2"

      - name: Build OO CLI
        run: |
          go build
        working-directory: ./cli/oo

      - name: Install current branch
        run: |
          go install github.com/openorch/openorch/cli/oo@${{ github.sha }}
