name: Go client build

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.23.2"

      - name: Build Go client
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          npm install @openapitools/openapi-generator-cli -g
          bash gen.sh
          go mod tidy
          go build
        working-directory: ./clients/go

      - name: Check for uncommitted changes
        if: false
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Uncommitted changes detected. Failing the build."
            git status
            git diff
            exit 1
          else
            echo "No changes detected."
          fi
