name: "Go SDK build"

on:
  push:

jobs:
  test:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.23.2"

      - name: Install dependencies
        run: |
          go mod tidy
        working-directory: sdk/go

      - name: Run tests
        run: |
          go test ./... -v -timeout=30s

          docker rm -f mypostgres
          docker run --name mypostgres -e POSTGRES_PASSWORD=mysecretpassword -e POSTGRES_DB=mydatabase -p 5432:5432 -d postgres

          # We rerun the tests with an SQL backend
          OPENORCH_DB=postgres \
            OPENORCH_DB_DEBUG=true \
            OPENORCH_DB_SQL_CONNECTION_STRING="postgres://postgres:mysecretpassword@localhost:5432/mydatabase?sslmode=disable" \
            go test ./... -v -timeout=30s
        working-directory: sdk/go

      - name: Test OpenAPI annotations
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          npm install @openapitools/openapi-generator-cli -g
          swag init --parseDependency
          openapi-generator-cli generate -i docs/swagger.yaml -g typescript-fetch -o ./genn
        working-directory: server
