name: "Go SDK build"

on:
  pull_request:

jobs:
  test:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.23.2"

      - name: Install dependencies
        run: |
          go mod tidy
        working-directory: sdk/go

      - name: Run tests
        run: |
          go test ./... -v -timeout=30s
        working-directory: sdk/go

      - name: Test OpenAPI annotations
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          npm install @openapitools/openapi-generator-cli -g
          swag init --parseDependency
          openapi-generator-cli generate -i docs/swagger.yaml -g typescript-fetch -o ./genn
        working-directory: server
