name: "E2E: local Docker Compose + run JS/TS client example"

on:
  push:
    branches:
      - "**"

jobs:
  build:
    timeout-minutes: 6
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Link local packages
        run: |
          npm link
          npm install
        working-directory: ./clients/js/client

      - name: Start docker containers
        run: |
          docker compose up openorch-backend -d

      - name: Run
        run: |
          npm install
          npm link @openorch/client
          npm run build

          HOST="127.0.0.1"
          PORT=58231

          while ! nc -z $HOST $PORT; do
            echo "Waiting for $HOST:$PORT to come online..."
            sleep 1
          done

          sleep 7

          set -e
          (
            node ./dist/index.js
          ) || (
            echo "Node.js script failed, running docker commands for diagnostics..."
            docker ps -a
            docker logs llama-cpp || true
            docker logs openorch-openorch-backend-1
            ifconfig
            exit 1
          )
        working-directory: ./clients/js/example
