name: "@1backend/client publish to npm"

on:
  push:
    branches:
      - main

jobs:
  publish:
    uses: ./.github/workflows/js-publish-reusable.yaml
    with:
      package_dir: ./clients/js/client
    secrets: inherit
