name: "@1backend/node publish to npm"

on:
  push:
    branches:
      - main

jobs:
  publish:
    uses: ./.github/workflows/js-publish-reusable.yaml
    with:
      package_dir: ./clients/js/node
      publish_enabled: false
    secrets: inherit
